### PR TITLE
add: feedback for demo gallery

### PR DESCRIPTION
**Pull request by iiakshat**

### CODE REVIEW

**Review by wwwillchen — COMMENTED** [review]
Thanks for contributing!

Could you add a screenshot and also update https://github.com/google/mesop/blob/ab9b47338187a262cc6d60679ca045447faee8e7/demo/main.py#L91 - then the demo will show up on the left-side nav menu

**Comment by iiakshat** [comment]
@wwwillchen I updated the 'feedback' in 'Misc' but cannot generate screenshots because of dependency errors. Can you still merge the pull request?

**Comment by wwwillchen** [comment]
> @wwwillchen I updated the 'feedback' in 'Misc' but cannot generate screenshots because of dependency errors. Can you still merge the pull request?

Looks like there's some formatting issues so I can't merge it yet. I'd recommend using GitHub codespaces to setup your dev env: https://google.github.io/mesop/internal/codespaces/ - it's a lot easier than doing it locally.

**Comment by iiakshat** [comment]
@wwwillchen Thank you for your feedback!

I've added the screenshot and updated mesop/demo/main.py  too, as requested. Could you please let me know if there are any other issues or steps I need to address to proceed with the merge?

**Comment by wwwillchen** [comment]
could you remove the screenshots - sorry about the churn (managing screenshots in the git repo has turned out to be quite troublesome)? See: #684. And then I think we can merge this.

**Comment by iiakshat** [comment]
> could you remove the screenshots - sorry about the churn (managing screenshots in the git repo has turned out to be quite troublesome)? See: #684. And then I think we can merge this.

done

**Comment by wwwillchen** [comment]
@iiakshat thanks for contributing!

**Pull request merged**
