### PR TITLE
Adds app url for mesop app maker.

### PR DESCRIPTION
**Pull request by richard-to**
I added Mesop App Maker to to Hugging Face. It's not ideal, since users need to create their own runner in Hugging Face Spaces. It's prettty easy to do. Just need to duplicate the Mesop App Runner space and set a "runner token". The runner token is just a basic way to block people from randomly using other people's runner instances.

Also added a link to the Hugging Face Jeopardy Mesop app.

### CODE REVIEW

**Comment by wwwillchen** [comment]
Just opened #849 which I'll try to do soon.

I think this is a good improvement, but it still feels a bit cumbersome.

Just to put an idea out there, what if we executed arbitrary user code in the same HF space and used something like https://github.com/zopefoundation/RestrictedPython to execute the user code with a restricted subset (e.g. you can call me.* and not much else).

Assuming the HF space doesn't have sensitive content (the only thing sensitive might be the API keys), but I could see this being useful even outside of LLM generation (e.g. user can give a URL like TypeScript playground: https://www.typescriptlang.org/play/?#code/G4QwTgBCC8EMwCgQVgJgQoA, to reproduce an issue or simply for sharing an example). WDYT?

**Review by wwwillchen — APPROVED** [review]

**Comment by richard-to** [comment]
Yes. Agreed not ideal. But figured it was better than nothing at the moment.

Ah, nice find. Yes, that could be useful, especially if each execution is itself sandboxed.

Definitely agree about the Mesop playground thing. That did cross my mind when I was trying to get viewer to work in a cheap and secure way.

Originally what I had wanted to do was use Docker in Docker. Then we could have an endpoint that could spawn docker containers and execute the code within a single container. But Hugging Face containers are more restricted in usage since Docker in Docker does require a bit more privileges to run.

**Comment by richard-to** [comment]
I looked into restricted python. I was able to use it fine. But it has a big blocker for now (can't handle type annotations yet...) https://github.com/zopefoundation/RestrictedPython/issues/219

**Comment by wwwillchen** [comment]
yeah, the workaround in the comment looks pretty promising

**Comment by richard-to** [comment]
> yeah, the workaround in the comment looks pretty promising

Yeah, I tried it out and it worked. Actually their code was very helpful in getting things set up. Still running into some errors, but I think I'm fairly close to getting it to work.

**Pull request merged**
