### PR TITLE
Upgrade ruff pre-commit hook

### PR DESCRIPTION
**Pull request by wwwillchen**
It was fighting some of the formatting changes I was making (due to a version skew between the version of the Ruff via VS code extension and the pre-commit Ruff)

### CODE REVIEW

**Comment by richard-to** [comment]
This change seems to include some other changes (like some of the security ones and also some link up dates).

**Comment by wwwillchen** [comment]
Fixed the commit history

**Review by richard-to — APPROVED** [review]
Looks like a failing test. But doesn't seem related to the changes here.

**Comment by wwwillchen** [comment]
> Looks like a failing test. But doesn't seem related to the changes here.

fixed it - the new version of ruff formats things a bit differently so that's why it was failing.

**Pull request merged**
